# Generated by Django 6.1 on 2026-08-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoultryBatch',
            fields=[
                ('batch_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('production_type', models.CharField(choices=[('BROILER', 'Broiler'), ('PULLET', 'Pullet'), ('LAYER', 'Layer')], max_length=16)),
                ('breed', models.CharField(blank=True, max_length=255)),
                ('initial_count', models.PositiveIntegerField()),
                ('current_count', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('mortality', models.PositiveIntegerField(default=0)),
                ('feed_consumed_kg', models.FloatField(default=0)),
                ('water_consumed_l', models.FloatField(default=0)),
                ('avg_sample_weight', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['log_date'],
            },
        ),
        migrations.CreateModel(
            name='BatchClosingReport',
            fields=[
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='closing_report', serialize=False, to='batches.poultrybatch')),
                ('closing_date', models.DateField(auto_now_add=True)),
                ('total_mortality_pct', models.FloatField()),
                ('feed_conversion_ratio', models.FloatField(null=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_variable_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost_price', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('total_margin', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
    ]
