# Generated by Django 6.1 on 2026-08-24 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poultrybatch',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poultrybatch',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='houses.poultryhouse'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='batches.poultrybatch'),
        ),
        migrations.AddConstraint(
            model_name='poultrybatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('house',), name='one_active_batch_per_house'),
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('batch', 'log_date'), name='one_daily_log_per_batch_per_day'),
        ),
    ]
