from django.conf import settings
from django.db import models

from apps.batches.models import PoultryBatch
from apps.core.models import Farm


class AlertRuleType(models.TextChoices):
    """Only LOW_STOCK (apps.alerts.services.check_low_stock, via StockMovement post_save) and
    CONSUMPTION_DEVIATION (check_consumption_deviation, via DailyLog post_save) are actually
    wired to a triggering signal in this codebase. VACCINE_DUE, PROFITABILITY_THRESHOLD and
    SANITARY_VOID_END exist as choices (and can be created manually via /api/alert-rules/) but
    nothing currently evaluates or fires them automatically — see docs/deviations.md.

    PROTOCOL_TASK (2026-08-25) rows are generated by apps.protocols.services.
    expand_protocol_to_alert_rules from a batch's ProtocolTemplate lines — same story as the
    three above: the row is created (and correctly re-created on protocol edits), but nothing
    evaluates `scheduled_date`/`trigger_time` to actually fire it, since this project has no
    Celery Beat schedule configured. See docs/deviations.md.

    WEIGHING_REMINDER (2026-08-25) is generated by apps.batches.services.sync_weighing_reminder
    from `PoultryBatch.weighing_frequency` — one recurring row per batch (SCHEDULED trigger_mode,
    `frequency` DAILY/WEEKLY/MONTHLY, no `scheduled_date`/`protocol_line`, unlike PROTOCOL_TASK),
    replaced whenever the frequency setting changes and removed when unset. Same as every other
    SCHEDULED rule here: created correctly, never actually fired (no Beat schedule)."""

    LOW_STOCK = 'LOW_STOCK', 'Low stock'
    VACCINE_DUE = 'VACCINE_DUE', 'Vaccine due'
    CONSUMPTION_DEVIATION = 'CONSUMPTION_DEVIATION', 'Consumption deviation'
    PROFITABILITY_THRESHOLD = 'PROFITABILITY_THRESHOLD', 'Profitability threshold'
    SANITARY_VOID_END = 'SANITARY_VOID_END', 'Sanitary void end'
    PROTOCOL_TASK = 'PROTOCOL_TASK', 'Protocol task'
    WEIGHING_REMINDER = 'WEIGHING_REMINDER', 'Weighing reminder'


class TriggerMode(models.TextChoices):
    EVENT = 'EVENT', 'Event'
    SCHEDULED = 'SCHEDULED', 'Scheduled'


class ScheduleFrequency(models.TextChoices):
    DAILY = 'DAILY', 'Daily'
    WEEKLY = 'WEEKLY', 'Weekly'
    MONTHLY = 'MONTHLY', 'Monthly'
    ONE_TIME = 'ONE_TIME', 'One time'


class AlertRule(models.Model):
    """EVENT rules set `threshold`; SCHEDULED rules set `trigger_time` + `frequency`.

    Only EVENT-mode rules (LOW_STOCK, CONSUMPTION_DEVIATION) actually fire in this codebase, via
    `apps.alerts.services.trigger_alert`'s `get_or_create` called from the two Django signal
    handlers in `apps.alerts.signals`. SCHEDULED-mode rules can be created through
    /api/alert-rules/ but nothing evaluates `trigger_time`/`frequency`/`active_days` — there is
    no Celery Beat schedule configured anywhere in this project (`config/celery.py` has no
    `beat_schedule`), so a SCHEDULED AlertRule never actually triggers an Alert. See
    docs/deviations.md.

    `batch` / `protocol_line` / `scheduled_date` (2026-08-25) are only ever set together, for
    PROTOCOL_TASK rows generated by apps.protocols.services.expand_protocol_to_alert_rules —
    every other rule type stays farm-scoped (all three null) exactly as before. `protocol_line`
    is `on_delete=CASCADE` so deleting (or editing away) a ProtocolTemplate line — or its whole
    category — cleans up the AlertRule rows it generated automatically, consistent with how
    deleting a ProtocolCategory already cascades to its ProtocolTemplate rows.
    """

    farm = models.ForeignKey(Farm, on_delete=models.CASCADE, related_name='alert_rules')
    rule_type = models.CharField(max_length=32, choices=AlertRuleType.choices)
    trigger_mode = models.CharField(max_length=16, choices=TriggerMode.choices)
    threshold = models.FloatField(null=True, blank=True)
    frequency = models.CharField(max_length=16, choices=ScheduleFrequency.choices, null=True, blank=True)
    trigger_time = models.TimeField(null=True, blank=True)
    active_days = models.CharField(max_length=64, blank=True)
    active = models.BooleanField(default=True)
    batch = models.ForeignKey(
        PoultryBatch, on_delete=models.CASCADE, null=True, blank=True, related_name='alert_rules',
        help_text='Set only for PROTOCOL_TASK rules generated from this batch\'s protocol.',
    )
    protocol_line = models.ForeignKey(
        'protocols.ProtocolTemplate', on_delete=models.CASCADE, null=True, blank=True, related_name='generated_alert_rules',
        help_text='The ProtocolTemplate row this PROTOCOL_TASK rule was expanded from.',
    )
    scheduled_date = models.DateField(
        null=True, blank=True,
        help_text='Calendar date this ONE_TIME PROTOCOL_TASK rule fires on — '
                   'batch.start_date + protocol_line.from_value converted to days.',
    )
    assignees = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name='assigned_alert_rules',
        help_text='Task-assignment targets (2026-08-26, docs/deviations.md Part 15; many-to-many since '
                   '2026-09-16, FIX 7) — only meaningful for WEIGHING_REMINDER rows, which (unlike '
                   "PROTOCOL_TASK) are stable/persistent rather than pruned each time they'd fire; see "
                   'apps.protocols.models.ProtocolTemplate.assignees for the protocol-line equivalent used '
                   'by every other "tâches à effectuer maintenant" entry. Several workers can share one '
                   'task: whoever completes it closes it for all of them.',
    )

    def __str__(self):
        return f'{self.rule_type} ({self.trigger_mode})'


class AlertStatus(models.TextChoices):
    NEW = 'NEW', 'New'
    SENT = 'SENT', 'Sent'
    RESOLVED = 'RESOLVED', 'Resolved'


class Alert(models.Model):
    """One triggered occurrence of an AlertRule. Created by `apps.alerts.services.trigger_alert`,
    which also queues an SmsMessage per opted-in recipient. `status` defaults to NEW and is
    otherwise unmanaged by any code path in this codebase — nothing transitions it to SENT or
    RESOLVED automatically (frontend/manual PATCH only, and no such PATCH endpoint currently
    exists either; see docs/deviations.md)."""

    rule = models.ForeignKey(AlertRule, on_delete=models.CASCADE, related_name='alerts')
    batch = models.ForeignKey(PoultryBatch, on_delete=models.CASCADE, null=True, blank=True, related_name='alerts')
    triggered_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=16, choices=AlertStatus.choices, default=AlertStatus.NEW)
    message = models.CharField(max_length=500, blank=True)
    severity = models.CharField(max_length=16, default='warning')
    # Sidebar notification-bell read state (2026-08-26) — distinct from `status`: `status`
    # tracks the underlying rule's SMS/resolution lifecycle (never actually transitioned past
    # NEW anywhere in this codebase, see docs/deviations.md #17), `is_read` only tracks whether
    # a user has seen this alert in the bell dropdown. Conflating the two would mean "marking
    # read" silently claims the underlying issue is resolved, which isn't true.
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ['-triggered_at']

    def __str__(self):
        return f'{self.rule.rule_type} · {self.triggered_at}'


class SmsStatus(models.TextChoices):
    PENDING = 'PENDING', 'Pending'
    SENT = 'SENT', 'Sent'
    DELIVERED = 'DELIVERED', 'Delivered'
    FAILED = 'FAILED', 'Failed'


class SmsMessage(models.Model):
    """retry_count / next_retry_at implement the exponential backoff required by the SMS gateway.
    idempotency_key prevents duplicates if Celery replays the task (e.g. worker crash after provider call).
    """

    alert = models.ForeignKey(Alert, on_delete=models.CASCADE, related_name='sms_messages')
    recipient = models.CharField(max_length=32)
    # This recipient's own text. A reminder shared by several assignees is one Alert with one
    # SMS each, greeted by name — sending `alert.message` gave all of them the first one's
    # greeting. Blank on rows written before the column existed: those send `alert.message`.
    body = models.TextField(blank=True, default='')
    idempotency_key = models.CharField(max_length=128, unique=True)
    provider_status = models.CharField(max_length=16, choices=SmsStatus.choices, default=SmsStatus.PENDING)
    provider = models.CharField(max_length=64, blank=True)
    retry_count = models.PositiveIntegerField(default=0)
    next_retry_at = models.DateTimeField(null=True, blank=True)
    sent_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.recipient} · {self.provider_status}'


class NotificationChannel(models.TextChoices):
    SMS = 'SMS', 'SMS'
    PUSH = 'PUSH', 'Push'
    EMAIL = 'EMAIL', 'Email'


class NotificationPreference(models.Model):
    """Per-user, per-alert-type volume control — reserves SMS for critical alerts."""

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='notification_preferences')
    rule_type = models.CharField(max_length=32, choices=AlertRuleType.choices)
    preferred_channel = models.CharField(max_length=8, choices=NotificationChannel.choices, default=NotificationChannel.SMS)
    active = models.BooleanField(default=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'rule_type'], name='one_preference_per_user_per_rule_type')
        ]

    def __str__(self):
        return f'{self.user_id} · {self.rule_type} · {self.preferred_channel}'


class PushSubscription(models.Model):
    """One browser Web Push endpoint a user has granted (2026-08-31). Populated by
    POST /api/push-subscriptions/ from the service-worker registration; used by
    apps.alerts.push.send_web_push_to_farm to deliver desktop notifications even when no
    Winchicken tab is open. A dead endpoint (404/410 from the push service) is deleted on the
    next send. `endpoint` is unique — re-subscribing the same browser upserts its keys."""

    farm = models.ForeignKey(Farm, on_delete=models.CASCADE, related_name='push_subscriptions')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='push_subscriptions')
    endpoint = models.URLField(max_length=1000, unique=True)
    p256dh = models.CharField(max_length=255)
    auth = models.CharField(max_length=255)
    user_agent = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.user_id} · {self.endpoint[:40]}'
