from datetime import timedelta

from celery import shared_task
from django.utils import timezone

from apps.alerts.models import SmsMessage, SmsStatus
from apps.alerts.providers import get_sms_provider

MAX_RETRIES = 5
BASE_BACKOFF_SECONDS = 30

# How close to `trigger_time` (in minutes) a recurring SCHEDULED rule is considered due —
# matches the beat interval below (5 minutes) so no tick is missed between two runs.
SCHEDULE_WINDOW_MINUTES = 5

WEEKDAY_CODES = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']


@shared_task(bind=True, max_retries=MAX_RETRIES)
def send_sms_task(self, sms_message_id: int):
    """Sends one SmsMessage. Idempotent via idempotency_key — safe to replay on worker crash.

    Never called synchronously from a view; always queued after the triggering write commits.
    """
    try:
        sms = SmsMessage.objects.get(pk=sms_message_id)
    except SmsMessage.DoesNotExist:
        return

    if sms.provider_status in (SmsStatus.SENT, SmsStatus.DELIVERED):
        return  # already handled — idempotency guard against task replay

    provider = get_sms_provider()
    result = provider.send(sms.recipient, sms.alert.message)

    if result['success']:
        sms.provider_status = SmsStatus.SENT
        sms.provider = result.get('provider_message_id') or 'unknown'
        sms.sent_at = timezone.now()
        sms.save(update_fields=['provider_status', 'provider', 'sent_at'])
        return

    sms.retry_count += 1
    if sms.retry_count >= MAX_RETRIES:
        sms.provider_status = SmsStatus.FAILED
        sms.save(update_fields=['provider_status', 'retry_count'])
        return

    backoff_seconds = BASE_BACKOFF_SECONDS * (2 ** (sms.retry_count - 1))
    sms.next_retry_at = timezone.now() + timedelta(seconds=backoff_seconds)
    sms.save(update_fields=['retry_count', 'next_retry_at'])
    raise self.retry(countdown=backoff_seconds)


@shared_task
def evaluate_scheduled_alert_rules():
    """Celery Beat periodic task (see config/celery.py's `beat_schedule`, runs every 5
    minutes) — the only place SCHEDULED-mode AlertRule rows are ever evaluated.

    Two kinds of SCHEDULED rule:
    - ONE_TIME with `fire_date` set (generated by
      apps.protocols.services.expand_protocol_to_alert_rules from a protocol line, or created
      directly through POST /api/alert-rules/): fires once, on that calendar date, then is
      marked `fired_at` so it never fires again.
    - Recurring (DAILY/WEEKLY) with `trigger_time` set: fires whenever "now" falls within
      SCHEDULE_WINDOW_MINUTES of `trigger_time`, and — for WEEKLY — today's weekday code is
      listed in `active_days` (comma-separated, e.g. "MON,WED,FRI"). Deduplicated the same way
      EVENT rules are: `apps.alerts.services.trigger_alert`'s Alert/SmsMessage creation already
      keys off idempotency, but a recurring rule can legitimately fire once per day, so no
      `fired_at` guard is applied to it (unlike the ONE_TIME case above).
    """
    from apps.alerts.models import AlertRule, AlertRuleType, ScheduleFrequency, TriggerMode
    from apps.alerts.services import trigger_alert

    now = timezone.localtime()
    today = now.date()

    one_time_due = AlertRule.objects.filter(
        trigger_mode=TriggerMode.SCHEDULED,
        frequency=ScheduleFrequency.ONE_TIME,
        active=True,
        fired_at__isnull=True,
        fire_date=today,
    ).select_related('farm')
    for rule in one_time_due:
        message = rule.note or rule.get_rule_type_display()
        if rule.batch_id:
            message = f'{message} — {rule.batch.batch_code}'
        trigger_alert(
            farm=rule.farm,
            rule_type=rule.rule_type,
            message=message,
            severity='warning' if rule.rule_type == AlertRuleType.VACCINE_DUE else 'info',
            batch=rule.batch,
            salt=str(today),
        )
        rule.fired_at = timezone.now()
        rule.save(update_fields=['fired_at'])

    recurring_due = AlertRule.objects.filter(
        trigger_mode=TriggerMode.SCHEDULED,
        active=True,
        trigger_time__isnull=False,
    ).exclude(frequency=ScheduleFrequency.ONE_TIME).select_related('farm')
    weekday_code = WEEKDAY_CODES[today.weekday()]
    for rule in recurring_due:
        # Already fired today: skip, so a rule that stays "due" across several beat ticks
        # inside its SCHEDULE_WINDOW_MINUTES window only ever creates one Alert per day.
        if rule.fired_at and rule.fired_at.date() == today:
            continue

        if rule.frequency == ScheduleFrequency.WEEKLY and rule.active_days:
            active_days = {day.strip().upper() for day in rule.active_days.split(',') if day.strip()}
            if weekday_code not in active_days:
                continue

        trigger_minutes = rule.trigger_time.hour * 60 + rule.trigger_time.minute
        now_minutes = now.hour * 60 + now.minute
        if abs(now_minutes - trigger_minutes) > SCHEDULE_WINDOW_MINUTES:
            continue

        trigger_alert(
            farm=rule.farm,
            rule_type=rule.rule_type,
            message=rule.note or rule.get_rule_type_display(),
            severity='info',
            batch=rule.batch,
            salt=str(today),
        )
        rule.fired_at = timezone.now()
        rule.save(update_fields=['fired_at'])
