# Generated by Django 6.1 on 2026-08-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('item_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('FEED', 'Feed'), ('VETERINARY', 'Veterinary'), ('EQUIPMENT', 'Equipment'), ('BEDDING', 'Bedding')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=16)),
                ('feed_stage', models.CharField(choices=[('STARTER', 'Starter'), ('GROWER', 'Grower'), ('FINISHER', 'Finisher'), ('PULLET_STAGE', 'Pullet stage'), ('LAYER_STAGE', 'Layer stage'), ('NOT_APPLICABLE', 'Not applicable')], default='NOT_APPLICABLE', max_length=16)),
                ('cold_chain_required', models.BooleanField(default=False)),
                ('alert_threshold', models.FloatField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.farm')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=4)),
                ('quantity', models.FloatField()),
                ('movement_date', models.DateField()),
                ('supplier_batch_number', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='batches.poultrybatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stockitem')),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('reconstitution_time', models.DateTimeField(blank=True, null=True)),
                ('doses_used', models.PositiveIntegerField()),
                ('status', models.CharField(default='SCHEDULED', max_length=32)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='batches.poultrybatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='stock.stockitem')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
