# Generated by Django 6.1 on 2026-08-28 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0006_protocoltemplate_quantity_per_day_and_more'),
        ('stock', '0003_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='protocol_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='protocols.protocoltemplate'),
        ),
    ]
