# Generated by Django 6.1 on 2026-08-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockmovement_protocol_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
