# Generated by Django 6.1 on 2026-08-31 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_hourly_rate'),
        ('stock', '0005_stockmovement_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_compositions', to='core.farm')),
                ('output_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions_as_output', to='stock.stockitem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockCompositionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='stock.stockcomposition')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_ingredients', to='stock.stockitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
