# Generated by Django 6.1 on 2026-08-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SENT', 'Sent'), ('RESOLVED', 'Resolved')], default='NEW', max_length=16)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('severity', models.CharField(default='warning', max_length=16)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('LOW_STOCK', 'Low stock'), ('VACCINE_DUE', 'Vaccine due'), ('CONSUMPTION_DEVIATION', 'Consumption deviation'), ('PROFITABILITY_THRESHOLD', 'Profitability threshold'), ('SANITARY_VOID_END', 'Sanitary void end')], max_length=32)),
                ('trigger_mode', models.CharField(choices=[('EVENT', 'Event'), ('SCHEDULED', 'Scheduled')], max_length=16)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('ONE_TIME', 'One time')], max_length=16, null=True)),
                ('trigger_time', models.TimeField(blank=True, null=True)),
                ('active_days', models.CharField(blank=True, max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('LOW_STOCK', 'Low stock'), ('VACCINE_DUE', 'Vaccine due'), ('CONSUMPTION_DEVIATION', 'Consumption deviation'), ('PROFITABILITY_THRESHOLD', 'Profitability threshold'), ('SANITARY_VOID_END', 'Sanitary void end')], max_length=32)),
                ('preferred_channel', models.CharField(choices=[('SMS', 'SMS'), ('PUSH', 'Push'), ('EMAIL', 'Email')], default='SMS', max_length=8)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=32)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('provider_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
