# Generated by Django 6.1 on 2026-08-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='batches.poultrybatch'),
        ),
    ]
