# Generated by Django 6.1 on 2026-09-22 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_initial"),
        ("batches", "0003_poultrybatch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_rules",
                to="batches.poultrybatch",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="fire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="fired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="note",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
