# Generated by Django 6.1 on 2026-08-26 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alert_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Task-assignment target (2026-08-26, docs/deviations.md Part 15) — only meaningful for WEIGHING_REMINDER rows, which (unlike PROTOCOL_TASK) are stable/persistent rather than pruned each time they\'d fire; see apps.protocols.models.ProtocolTemplate.assigned_to for the protocol-line equivalent used by every other "tâches à effectuer maintenant" entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alert_rules', to=settings.AUTH_USER_MODEL),
        ),
    ]
