# Generated by Django 6.1 on 2026-09-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alertrule_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
