# Generated by Django 6.1 on 2026-09-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_smsmessage_body'),
        ('batches', '0006_remove_poultrybatch_current_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-triggered_at'], name='alert_triggered_at_desc'),
        ),
    ]
