# Generated by Django 6.1 on 2026-08-26 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_farm_singleton_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name_snapshot', models.CharField(max_length=255)),
                ('action', models.CharField(help_text='e.g. "batch.created", "protocol.updated", "farm.reset".', max_length=64)),
                ('target_description', models.CharField(help_text='Human-readable, e.g. "Bande Printemps 2026".', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_entries', to='core.farm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
