# Generated by Django 6.1 on 2026-08-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='civility',
            field=models.CharField(choices=[('M', 'Monsieur'), ('MME', 'Madame')], default='M', max_length=4),
        ),
    ]
