# Generated by Django 6.1 on 2026-08-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_civility'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Payroll rate (2026-08-27, Salaires module) — nullable: not every role is paid hourly (e.g. Admin/Farm Manager), so no value is forced. Set from /dashboard/employees by Admin/Farm Manager. A user with no rate set is skipped by monthly salary calculation, not treated as a 0-rate employee.', max_digits=10, null=True),
        ),
    ]
