# Generated by Django 6.1 on 2026-08-24 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_initial'),
        ('houses', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentFault',
            fields=[
                ('fault_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('fault_description', models.CharField(max_length=1000)),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('repaired_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='REPORTED', max_length=32)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_faults', to='houses.poultryhouse')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_faults', to='stock.stockitem')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_faults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='UnusualCase',
            fields=[
                ('case_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('case_description', models.CharField(max_length=1000)),
                ('case_date', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unusual_cases', to='batches.poultrybatch')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases_as_farmer', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases_as_worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-case_date'],
            },
        ),
    ]
