# Generated by Django 6.1 on 2026-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentfault",
            name="status",
            field=models.CharField(
                choices=[
                    ("REPORTED", "Reported"),
                    ("IN_PROGRESS", "In progress"),
                    ("REPAIRED", "Repaired"),
                ],
                default="REPORTED",
                max_length=32,
            ),
        ),
    ]
