# Generated by Django 6.1 on 2026-08-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unusualcase',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unusualcase',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
