# Generated by Django 6.1 on 2026-08-27 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_unusualcase_resolved_unusualcase_resolved_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentfault',
            name='resolved_by',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='resolved_faults', to=settings.AUTH_USER_MODEL,
                help_text='Who called the resolve action (2026-08-27, "Historique" tab, docs/deviations.md — '
                           'Feature 5) — set only by EquipmentFaultResolveView, never by the plain create/update path.',
            ),
        ),
        migrations.AddField(
            model_name='unusualcase',
            name='resolved_by',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='resolved_cases', to=settings.AUTH_USER_MODEL,
                help_text='Who called the resolve action (2026-08-27, "Historique" tab, docs/deviations.md — '
                           'Feature 5) — set only by UnusualCaseResolveView, never by the plain create/update path.',
            ),
        ),
    ]
