# Generated by Django 6.1 on 2026-08-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FEEDING', 'Feeding'), ('TEMPERATURE', 'Temperature'), ('HEALTH', 'Health & treatment'), ('VACCINATION', 'Vaccination'), ('CLEANING', 'Cleaning')], max_length=16)),
                ('from_value', models.PositiveIntegerField()),
                ('from_unit', models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month')], default='DAY', max_length=8)),
                ('to_value', models.PositiveIntegerField(blank=True, null=True)),
                ('to_unit', models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month')], default='DAY', max_length=8)),
                ('until_end', models.BooleanField(default=False)),
                ('what', models.CharField(max_length=255)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_lines', to='houses.poultryhouse')),
            ],
            options={
                'ordering': ['category', 'from_value'],
            },
        ),
    ]
