# Generated by Django 6.1 on 2026-08-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0003_protocoltemplate_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('protocol_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='protocols.protocoltemplate')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
