# Generated by Django 6.1 on 2026-08-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0004_protocoltimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoltimeslot',
            name='end_time',
            # No default: ProtocolTimeSlot had no writable UI before this migration (Bug 1 fix,
            # docs/deviations.md) — zero existing rows in any environment, confirmed before
            # writing this migration, so a straight NOT NULL add is safe.
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
