# Generated by Django 6.1 on 2026-08-28 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0005_protocoltimeslot_end_time'),
        ('stock', '0003_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoltemplate',
            name='quantity_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocoltemplate',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_lines', to='stock.stockitem'),
        ),
    ]
