# Generated by Django 6.1 on 2026-08-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0006_protocoltemplate_quantity_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocoltemplate',
            name='dose_per_bird',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
