# Generated by Django 6.1 on 2026-08-31 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0006_remove_poultrybatch_current_count'),
        ('protocols', '0007_protocoltemplate_dose_per_bird'),
        ('stock', '0005_stockmovement_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='batches.poultrybatch')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_completions', to=settings.AUTH_USER_MODEL)),
                ('protocol_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='protocols.protocoltemplate')),
                ('stock_movement', models.ForeignKey(blank=True, help_text='The OUT movement this completion created, if the row had a linked resource + quantity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.stockmovement')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='protocols.protocoltimeslot')),
            ],
            options={
                'ordering': ['-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('protocol_template', 'batch', 'date', 'time_slot'), name='uniq_task_completion_per_occurrence', nulls_distinct=False)],
            },
        ),
    ]
