# Generated by Django 6.1 on 2026-08-24 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoultryHouse',
            fields=[
                ('house_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size_m2', models.PositiveIntegerField(blank=True, null=True)),
                ('max_capacity', models.PositiveIntegerField()),
                ('last_disinfection_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='core.farm')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
